### ISSUE TITLE
哥,能不能注解补上

### ISSUE THREAD

**Issue by MrXuCh** [tangaiyun/redislimiter-spring-boot#2]
哥,能不能注解补上,看不懂啊,小白一枚

**Comment by tangaiyun** [comment]
注解补上，啥意思？注解上补上注释？

**Comment by tangaiyun** [comment]
https://github.com/tangaiyun/redislimiter-spring-boot/blob/master/README-CN.md

**Comment by MrXuCh** [comment]
哈哈,我的意思是代码里的注释,我看代码都没有注释,对于小白看代码,没有注释比较累,啊哈哈哈

**Comment by huangnian630** [comment]
> https://github.com/tangaiyun/redislimiter-spring-boot/blob/master/README-CN.md

如果每5秒执行一次，是不是需要改lua脚本或者使用第二个判断让单位秒也能进入第二个逻辑，当时你没这样做的目的是不是有并发问题呢？
