### ISSUE TITLE
大神每5秒只能调用1次如何配置？

### ISSUE THREAD

**Issue by huangnian630** [tangaiyun/redislimiter-spring-boot#4]
@RateLimiter(base = "#Headers['X-Real-IP']", permits = 1)
次数有了，时间呢？

**Comment by tangaiyun** [comment]
目前不支持每秒x次，每分钟x次，每小时x次，每天x次这样的，不支持每5秒一次这类配置，一个可能的做法是改成每分钟12次

**Comment by tangaiyun** [comment]
貌似不支持。。。
